### ISSUE TITLE
Configure GitHub action to check coding style

### ISSUE THREAD

**Issue by taquangtrung** [sbip-sg/llvm-project#11]
@thanhtoantnt: can you investigate if we can use Clang-format to set up a GitHub action, similar to the Cargo format feature in Rust?

https://clang.llvm.org/docs/ClangFormat.html

**Comment by thanhtoantnt** [comment]
@taquangtrung How about this [action](https://github.com/marketplace/actions/git-clang-format-action). I just created a branch using this one. If it is okay, I will create a PR.
