### ISSUE TITLE
Rename branches `sbip-llvm-***` to `llvm-sbip-***`

### ISSUE THREAD

**Issue by taquangtrung** [sbip-sg/llvm-project#16]
I renamed the branches `sbip-llvm-13`, `sbip-llvm-14` to `llvm-sbip-13`, `llvm-sbip-14` to match the branch names with the release names.

@thanhtoantnt: you may need to update your local code base.

**Comment by thanhtoantnt** [comment]
I have done it. Could we close this issue now?
