### ISSUE TITLE
Release pre-built version of SBIP's llvm-project

### ISSUE THREAD

**Issue by taquangtrung** [sbip-sg/llvm-project#6]
We should release a pre-built LLVM version so that users don't need to build LLVM by themself (which is time-consuming)

**Comment by taquangtrung** [comment]
@thanhtoantnt : can you investigate how to do it?

We should release the pre-built LLVM like the way the official LLVM repository has been releasing: https://github.com/llvm/llvm-project/releases/

**Comment by thanhtoantnt** [comment]
@taquangtrung Can we close this issue since we have release versions now https://github.com/sbip-sg/llvm-project/releases

**Comment by thanhtoantnt** [comment]
@taquangtrung Can we close this issue since we have release versions now https://github.com/sbip-sg/llvm-project/releases

**Comment by thanhtoantnt** [comment]
@taquangtrung I change the compilation instruction to the latest update in Verazt. Hence, the release of version 3 is now similar to version 2 and 1.
